import type { Level } from './types';

const MAIN_ID = 'main-block';

export const levels: Level[] = [
	[
		{ id: 's0', type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: 'v1', type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: 's2', type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: 's3', type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: 's4', type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: 'h5', type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: 's6', type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: 's7', type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: 'h8', type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: 'h10', type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'v0', type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: 's1', type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: 's2', type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: 's3', type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: 's4', type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: 'h5', type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: 'h6', type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: 'v7', type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: 'v8', type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: 'h9', type: 'hero', x: 2, y: 3, w: 2, h: 2 }
	],
	[
		{ id: 's0', type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: 's1', type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: 'h2', type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: 'h3', type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: 'v4', type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: 's5', type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: 'h6', type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: 's7', type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: 'h8', type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'h0', type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: 'h1', type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: 'v2', type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: 's3', type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: 's4', type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: 'h5', type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: 's6', type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: 'h7', type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: 's8', type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'h0', type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: 's1', type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: 'v2', type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: 's3', type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: 'h4', type: 'hero', x: 1, y: 1, w: 2, h: 2 },
		{ id: 's5', type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: 'v6', type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: 'v7', type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: 's8', type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: 'v9', type: 'vertical', x: 2, y: 3, w: 1, h: 2 }
	],
	[
		{ id: 's0', type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: 's1', type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: 'h2', type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: 'h3', type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: 'v4', type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: 'v5', type: 'vertical', x: 1, y: 2, w: 1, h: 2 },
		{ id: 's6', type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: 'v7', type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: 's8', type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'v0', type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: 'h1', type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: 's2', type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: 'v3', type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: 'h4', type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: 's5', type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: 'v6', type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: 's7', type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: 'v8', type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: 's9', type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: 'v0', type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: 'v1', type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: 'h2', type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: 'h3', type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: 'v4', type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: 'v5', type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: 's6', type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: 's7', type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: 's8', type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: 's9', type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: 'h0', type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: 'h1', type: 'horizontal', x: 2, y: 0, w: 2, h: 1 },
		{ id: 'v2', type: 'vertical', x: 2, y: 1, w: 1, h: 2 },
		{ id: 's3', type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: 'h4', type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: 'v5', type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: 's6', type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: 'h7', type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: 's8', type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: 's9', type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: 's0', type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: 'h1', type: 'horizontal', x: 1, y: 0, w: 2, h: 1 },
		{ id: 's2', type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: 'v3', type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: 's4', type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: 'v5', type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: 'v6', type: 'vertical', x: 1, y: 2, w: 1, h: 2 },
		{ id: 's7', type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: 'h8', type: 'hero', x: 2, y: 3, w: 2, h: 2 },
		{ id: 'h9', type: 'horizontal', x: 0, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 's0', type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: 's1', type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: 'h2', type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: 'h3', type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: 'v4', type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: 's5', type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: 'v6', type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: 'v7', type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: 's8', type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'h0', type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: 's1', type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: 'v2', type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: 's3', type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: 'h4', type: 'hero', x: 1, y: 1, w: 2, h: 2 },
		{ id: 's5', type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: 's6', type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: 'v7', type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: 'h8', type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'h0', type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: 's1', type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: 's2', type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: 'h3', type: 'horizontal', x: 2, y: 1, w: 2, h: 1 },
		{ id: 'v4', type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: 's5', type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: 'v6', type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: 's7', type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: 'v8', type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: 'h9', type: 'horizontal', x: 0, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 's0', type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: 'h1', type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: 's2', type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: 'h3', type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: 'h4', type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: 's5', type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: 'v6', type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: 'h7', type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: 's8', type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 's0', type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: 's1', type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: 'h2', type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: 's3', type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: 's4', type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: 'h5', type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: 'h6', type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: 'v7', type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: 'v8', type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: 'h9', type: 'horizontal', x: 0, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'h0', type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: 'v1', type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: 'v2', type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: 'h3', type: 'hero', x: 0, y: 1, w: 2, h: 2 },
		{ id: 'h4', type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: 'h5', type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: 's6', type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: 's7', type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: 's8', type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: 's9', type: 'soldier', x: 1, y: 4, w: 1, h: 1 }
	],
	[
		{ id: 's0', type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: 'v1', type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: 's2', type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: 'h3', type: 'horizontal', x: 2, y: 1, w: 2, h: 1 },
		{ id: 'h4', type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: 'h5', type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: 's6', type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: 's7', type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: 'h8', type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: 'v0', type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: 's1', type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: 'h2', type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: 's3', type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: 'v4', type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: 's5', type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: 'v6', type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: 'v7', type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: 's8', type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: 'h9', type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	]
];
