import type { Level } from './types';

let counter = 0;
const getid = () => `${counter++}`;
const mainid = 'HERO';

export const levels: Level[] = [
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 3, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 2, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 2, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 2, y: 3, w: 2, h: 2 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 1, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 0, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 3, w: 1, h: 2 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 1, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 1, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: mainid, type: 'hero', x: 0, y: 3, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 1, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	],
	[
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 1, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: mainid, type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: mainid, type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 }
	],
	[
		{ id: mainid, type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 3, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: mainid, type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'horizontal', x: 0, y: 0, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 2, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 }
	],
	[
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: mainid, type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 1, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 3, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 0, y: 1, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 2, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 1, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: mainid, type: 'hero', x: 0, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 0, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 3, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 2, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 3, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 2, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 0, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 2, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 0, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 0, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'soldier', x: 2, y: 1, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 2, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 0, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 1, y: 1, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 2, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 1, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'soldier', x: 0, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 0, w: 1, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 0, y: 1, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 2, y: 1, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 3, w: 2, h: 1 },
		{ id: getid(), type: 'soldier', x: 1, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'horizontal', x: 2, y: 4, w: 2, h: 1 }
	],
	[
		{ id: getid(), type: 'vertical', x: 0, y: 0, w: 1, h: 2 },
		{ id: mainid, type: 'hero', x: 1, y: 0, w: 2, h: 2 },
		{ id: getid(), type: 'vertical', x: 3, y: 0, w: 1, h: 2 },
		{ id: getid(), type: 'vertical', x: 0, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'horizontal', x: 1, y: 2, w: 2, h: 1 },
		{ id: getid(), type: 'vertical', x: 3, y: 2, w: 1, h: 2 },
		{ id: getid(), type: 'soldier', x: 1, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 2, y: 3, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 0, y: 4, w: 1, h: 1 },
		{ id: getid(), type: 'soldier', x: 3, y: 4, w: 1, h: 1 }
	]
];
